name: Portfolio Workflow
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
      - "dev"
      - "feat/**"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
